// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN1pb5p58dR_wm1yV3WRdwit8x8sJQKaE',
    appId: '1:103543831309:web:b0ad6ad8995425beccce44',
    messagingSenderId: '103543831309',
    projectId: 'lead-management-app-74c44',
    authDomain: 'lead-management-app-74c44.firebaseapp.com',
    storageBucket: 'lead-management-app-74c44.firebasestorage.app',
    measurementId: 'G-DZ2YNV949D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfUXznu6MHMTFRw13fo3pknoZQ-GTA3Jg',
    appId: '1:103543831309:android:8960a81c865ee57bccce44',
    messagingSenderId: '103543831309',
    projectId: 'lead-management-app-74c44',
    storageBucket: 'lead-management-app-74c44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXJeJyLFuwNMbGqBf_TF27sniUu51UH5E',
    appId: '1:103543831309:ios:10dca50b3a60ab19ccce44',
    messagingSenderId: '103543831309',
    projectId: 'lead-management-app-74c44',
    storageBucket: 'lead-management-app-74c44.firebasestorage.app',
    iosBundleId: 'com.example.bbmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXJeJyLFuwNMbGqBf_TF27sniUu51UH5E',
    appId: '1:103543831309:ios:10dca50b3a60ab19ccce44',
    messagingSenderId: '103543831309',
    projectId: 'lead-management-app-74c44',
    storageBucket: 'lead-management-app-74c44.firebasestorage.app',
    iosBundleId: 'com.example.bbmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN1pb5p58dR_wm1yV3WRdwit8x8sJQKaE',
    appId: '1:103543831309:web:8a9e25a6ca5f4d2bccce44',
    messagingSenderId: '103543831309',
    projectId: 'lead-management-app-74c44',
    authDomain: 'lead-management-app-74c44.firebaseapp.com',
    storageBucket: 'lead-management-app-74c44.firebasestorage.app',
    measurementId: 'G-2DV6P8M2QR',
  );
}
